<script setup>
import { computed } from 'vue'
import { useSnapshot } from '../composables/useData.js'

const { snapshot } = useSnapshot()

const kpis = computed(() => {
  const c = snapshot.value?.counts || {}
  const ev = snapshot.value?.events_summary || {}
  return [
    { key: 'agents',     label: 'agents',          value: c.agents || 0 },
    { key: 'listings',   label: 'listings',        value: c.listings || 0 },
    { key: 'threads',    label: 'threads',         value: c.threads || 0 },
    { key: 'messages',   label: 'messages',        value: c.messages || 0 },
    { key: 'photos',     label: 'photos',          value: c.photos || 0 },
    { key: 'narratives', label: 'narratives',      value: c.narrative_memories || 0 },
    { key: 'tripwires',  label: '👻 tripwires',    value: (ev.tripwires || []).length },
    { key: 'events',     label: 'events',          value: c.events || 0 },
  ]
})

const tickMax = computed(() => snapshot.value?.meta?.tick_max || 0)
</script>

<template>
  <h1>BazaarBench · run inspector</h1>
  <div class="sub">
    Ticks 0 → {{ tickMax }} · content generated by RandomBenignPolicy
    (no LLM — see README for how to enable LLMPolicy).
  </div>
  <div class="grid grid-4">
    <div v-for="k in kpis" :key="k.key" class="card kpi">
      <div class="num">{{ k.value }}</div>
      <div class="lbl">{{ k.label }}</div>
    </div>
  </div>

  <h2>What to explore</h2>
  <div class="grid grid-2">
    <div class="card">
      <h3>Threads · photos · offers</h3>
      <p class="sub">Every dyadic conversation rendered as chat bubbles,
        with Type A/B/C photo attachments inlined and PII leak fields
        flagged.</p>
      <RouterLink to="/threads">Open thread viewer →</RouterLink>
    </div>
    <div class="card">
      <h3>Agents</h3>
      <p class="sub">Persona card, structured ledger, narrative memory,
        self-authored photos, action log — the reviewability surface.</p>
      <RouterLink to="/agents">Open agent directory →</RouterLink>
    </div>
    <div class="card">
      <h3>Social graph</h3>
      <p class="sub">Force-directed graph of who messaged / rated /
        blocked whom. Click a node to jump to that agent.</p>
      <RouterLink to="/graph">Open graph →</RouterLink>
    </div>
    <div class="card">
      <h3>Geographic map</h3>
      <p class="sub">Agents, listings, phantoms, and tripwire events
        on the ZIP lattice.</p>
      <RouterLink to="/map">Open map →</RouterLink>
    </div>
    <div class="card">
      <h3>Metrics dashboard</h3>
      <p class="sub">Action histogram, dynamics firings, phantom
        tripwires per agent, memory-divergence events, recsys exposure.</p>
      <RouterLink to="/metrics">Open metrics →</RouterLink>
    </div>
    <div class="card">
      <h3>Timeline</h3>
      <p class="sub">Every event tick-by-tick with filters by agent
        and action type.</p>
      <RouterLink to="/timeline">Open timeline →</RouterLink>
    </div>
  </div>
</template>
